correct the github action

diff --git a/.github/workflows/build_push_aws.yml b/.github/workflows/build_push_aws.yml
--- a/.github/workflows/build_push_aws.yml
+++ b/.github/workflows/build_push_aws.yml
@@ -84,6 +84,8 @@ jobs:
         username: ${{secrets.AMAZON_USER}}
         key: ${{secrets.AMAZON_PEM}}
         script: |
+          set -e # Exit immediately if a command exits with a non-zero status.
+          echo "Deploying to EC2..."
           ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
           REPO_NAME="${{ env.REPO_NAME }}"
           AWS_ACCESS_KEY_ID="${{ secrets.AMAZON_ACCESS_KEY }}"
@@ -130,6 +132,8 @@ jobs:
 
           echo "Remove Unused Images:"
           docker image prune -a --force --filter "until=24h"
+
+          echo "Deployment to EC2 completed."
 
 
 
